monaco.editor.defineTheme('github', {
	base: 'vs',
	inherit: false,
	rules: [
		{
			foreground: '6E7781',
			token: 'comment',
		},
		{
			foreground: '6E7781',
			token: 'punctuation.definition.comment',
		},
		{
			foreground: '6E7781',
			token: 'string.comment',
		},
		{
			foreground: 'CF222E',
			token: 'constant.other.placeholder',
		},
		{
			foreground: 'CF222E',
			token: 'constant.character',
		},
		{
			foreground: '0550AE',
			token: 'constant',
		},
		{
			foreground: '0550AE',
			token: 'entity.name.constant',
		},
		{
			foreground: '0550AE',
			token: 'variable.other.constant',
		},
		{
			foreground: '0550AE',
			token: 'variable.other.enummember',
		},
		{
			foreground: '0550AE',
			token: 'variable.language',
		},
		{
			foreground: '0550AE',
			token: 'entity',
		},
		{
			foreground: '953800',
			token: 'entity.name',
		},
		{
			foreground: '953800',
			token: 'meta.export.default',
		},
		{
			foreground: '953800',
			token: 'meta.definition.variable',
		},
		{
			foreground: '24292F',
			token: 'variable.parameter.function',
		},
		{
			foreground: '24292F',
			token: 'meta.jsx.children',
		},
		{
			foreground: '24292F',
			token: 'meta.block',
		},
		{
			foreground: '24292F',
			token: 'meta.tag.attributes',
		},
		{
			foreground: '24292F',
			token: 'entity.name.constant',
		},
		{
			foreground: '24292F',
			token: 'meta.object.member',
		},
		{
			foreground: '24292F',
			token: 'meta.embedded.expression',
		},
		{
			foreground: '8250DF',
			token: 'entity.name.function',
		},
		{
			foreground: '116329',
			token: 'entity.name.tag',
		},
		{
			foreground: '116329',
			token: 'support.class.component',
		},
		{
			foreground: 'CF222E',
			token: 'keyword',
		},
		{
			foreground: 'CF222E',
			token: 'storage',
		},
		{
			foreground: 'CF222E',
			token: 'storage.type',
		},
		{
			foreground: '24292F',
			token: 'storage.modifier.package',
		},
		{
			foreground: '24292F',
			token: 'storage.modifier.import',
		},
		{
			foreground: '24292F',
			token: 'storage.type.java',
		},
		{
			foreground: '0A3069',
			token: 'string',
		},
		{
			foreground: '0A3069',
			token: 'string punctuation.section.embedded source',
		},
		{
			foreground: '0550AE',
			token: 'support',
		},
		{
			foreground: '0550AE',
			token: 'meta.property-name',
		},
		{
			foreground: '953800',
			token: 'variable',
		},
		{
			foreground: '24292F',
			token: 'variable.other',
		},
		{
			foreground: '82071E',
			fontStyle: 'italic',
			token: 'invalid.broken',
		},
		{
			foreground: '82071E',
			fontStyle: 'italic',
			token: 'invalid.deprecated',
		},
		{
			foreground: '82071E',
			fontStyle: 'italic',
			token: 'invalid.illegal',
		},
		{
			foreground: '82071E',
			fontStyle: 'italic',
			token: 'invalid.unimplemented',
		},
		{
			foreground: 'F6F8FA',
			background: 'CF222E',
			fontStyle: 'italic underline',
			token: 'carriage-return',
		},
		{
			foreground: '82071E',
			token: 'message.error',
		},
		{
			foreground: '0550AE',
			token: 'string variable',
		},
		{
			foreground: '0A3069',
			token: 'source.regexp',
		},
		{
			foreground: '0A3069',
			token: 'string.regexp',
		},
		{
			foreground: '0A3069',
			token: 'string.regexp.character-class',
		},
		{
			foreground: '0A3069',
			token: 'string.regexp constant.character.escape',
		},
		{
			foreground: '0A3069',
			token: 'string.regexp source.ruby.embedded',
		},
		{
			foreground: '0A3069',
			token: 'string.regexp string.regexp.arbitrary-repitition',
		},
		{
			foreground: '116329',
			fontStyle: 'bold',
			token: 'string.regexp constant.character.escape',
		},
		{
			foreground: '0550AE',
			token: 'support.constant',
		},
		{
			foreground: '0550AE',
			token: 'support.variable',
		},
		{
			foreground: '116329',
			token: 'support.type.property-name.json',
		},
		{
			foreground: '0550AE',
			token: 'meta.module-reference',
		},
		{
			foreground: '953800',
			token: 'punctuation.definition.list.begin.markdown',
		},
		{
			foreground: '0550AE',
			fontStyle: 'bold',
			token: 'markup.heading',
		},
		{
			foreground: '0550AE',
			fontStyle: 'bold',
			token: 'markup.heading entity.name',
		},
		{
			foreground: '116329',
			token: 'markup.quote',
		},
		{
			foreground: '24292F',
			fontStyle: 'italic',
			token: 'markup.italic',
		},
		{
			foreground: '24292F',
			fontStyle: 'bold',
			token: 'markup.bold',
		},
		{
			fontStyle: 'underline',
			token: 'markup.underline',
		},
		{
			fontStyle: 'strikethrough',
			token: 'markup.strikethrough',
		},
		{
			foreground: '0550AE',
			token: 'markup.inline.raw',
		},
		{
			foreground: '82071E',
			background: 'FFEBE9',
			token: 'markup.deleted',
		},
		{
			foreground: '82071E',
			background: 'FFEBE9',
			token: 'meta.diff.header.from-file',
		},
		{
			foreground: '82071E',
			background: 'FFEBE9',
			token: 'punctuation.definition.deleted',
		},
		{
			foreground: 'CF222E',
			token: 'punctuation.section.embedded',
		},
		{
			foreground: '116329',
			background: 'DAFBE1',
			token: 'markup.inserted',
		},
		{
			foreground: '116329',
			background: 'DAFBE1',
			token: 'meta.diff.header.to-file',
		},
		{
			foreground: '116329',
			background: 'DAFBE1',
			token: 'punctuation.definition.inserted',
		},
		{
			foreground: '953800',
			background: 'FFD8B5',
			token: 'markup.changed',
		},
		{
			foreground: '953800',
			background: 'FFD8B5',
			token: 'punctuation.definition.changed',
		},
		{
			foreground: 'EAEEF2',
			background: '0550AE',
			token: 'markup.ignored',
		},
		{
			foreground: 'EAEEF2',
			background: '0550AE',
			token: 'markup.untracked',
		},
		{
			foreground: '8250DF',
			fontStyle: 'bold',
			token: 'meta.diff.range',
		},
		{
			foreground: '0550AE',
			token: 'meta.diff.header',
		},
		{
			foreground: '0550AE',
			fontStyle: 'bold',
			token: 'meta.separator',
		},
		{
			foreground: '0550AE',
			token: 'meta.output',
		},
		{
			foreground: '57606A',
			token: 'brackethighlighter.tag',
		},
		{
			foreground: '57606A',
			token: 'brackethighlighter.curly',
		},
		{
			foreground: '57606A',
			token: 'brackethighlighter.round',
		},
		{
			foreground: '57606A',
			token: 'brackethighlighter.square',
		},
		{
			foreground: '57606A',
			token: 'brackethighlighter.angle',
		},
		{
			foreground: '57606A',
			token: 'brackethighlighter.quote',
		},
		{
			foreground: '82071E',
			token: 'brackethighlighter.unmatched',
		},
		{
			foreground: '0A3069',
			token: 'constant.other.reference.link',
		},
		{
			foreground: '0A3069',
			token: 'string.other.link',
		},
		{
			foreground: '316BCD',
			token: 'token.info-token',
		},
		{
			foreground: 'CD9731',
			token: 'token.warn-token',
		},
		{
			foreground: 'CD3131',
			token: 'token.error-token',
		},
		{
			foreground: '800080',
			token: 'token.debug-token',
		},
	],
	colors: {
		'activityBar.activeBorder': '#fd8c73',
		'activityBar.background': '#ffffff',
		'activityBar.border': '#d0d7de',
		'activityBar.foreground': '#24292f',
		'activityBar.inactiveForeground': '#57606a',
		'activityBarBadge.background': '#0969da',
		'activityBarBadge.foreground': '#ffffff',
		'badge.background': '#0969da',
		'badge.foreground': '#ffffff',
		'breadcrumb.activeSelectionForeground': '#57606a',
		'breadcrumb.focusForeground': '#24292f',
		'breadcrumb.foreground': '#57606a',
		'breadcrumbPicker.background': '#ffffff',
		'button.background': '#2da44e',
		'button.foreground': '#ffffff',
		'button.hoverBackground': '#2c974b',
		'button.secondaryBackground': '#ebecf0',
		'button.secondaryForeground': '#24292f',
		'button.secondaryHoverBackground': '#f3f4f6',
		'checkbox.background': '#f6f8fa',
		'checkbox.border': '#d0d7de',
		'debugConsole.errorForeground': '#cf222e',
		'debugConsole.infoForeground': '#57606a',
		'debugConsole.sourceForeground': '#9a6700',
		'debugConsole.warningForeground': '#7d4e00',
		'debugConsoleInputIcon.foreground': '#6639ba',
		'debugIcon.breakpointForeground': '#cf222e',
		'debugTokenExpression.boolean': '#116329',
		'debugTokenExpression.error': '#a40e26',
		'debugTokenExpression.name': '#0550ae',
		'debugTokenExpression.number': '#116329',
		'debugTokenExpression.string': '#0a3069',
		'debugTokenExpression.value': '#0a3069',
		'debugToolBar.background': '#ffffff',
		descriptionForeground: '#57606a',
		'diffEditor.insertedLineBackground': '#aceebb4d',
		'diffEditor.insertedTextBackground': '#6fdd8b80',
		'diffEditor.removedLineBackground': '#ffcecb4d',
		'diffEditor.removedTextBackground': '#ff818266',
		'dropdown.background': '#ffffff',
		'dropdown.border': '#d0d7de',
		'dropdown.foreground': '#24292f',
		'dropdown.listBackground': '#ffffff',
		'editor.background': '#ffffff',
		'editor.findMatchBackground': '#bf8700',
		'editor.findMatchHighlightBackground': '#fae17d80',
		'editor.focusedStackFrameHighlightBackground': '#4ac26b66',
		'editor.foldBackground': '#6e77811a',
		'editor.foreground': '#24292f',
		'editor.lineHighlightBackground': '#eaeef280',
		'editor.linkedEditingBackground': '#0969da12',
		'editor.selectionHighlightBackground': '#4ac26b40',
		'editor.stackFrameHighlightBackground': '#d4a72c66',
		'editor.wordHighlightBackground': '#eaeef280',
		'editor.wordHighlightBorder': '#afb8c199',
		'editor.wordHighlightStrongBackground': '#afb8c14d',
		'editor.wordHighlightStrongBorder': '#afb8c199',
		'editorBracketHighlight.foreground1': '#0969da',
		'editorBracketHighlight.foreground2': '#1a7f37',
		'editorBracketHighlight.foreground3': '#9a6700',
		'editorBracketHighlight.foreground4': '#cf222e',
		'editorBracketHighlight.foreground5': '#bf3989',
		'editorBracketHighlight.foreground6': '#8250df',
		'editorBracketHighlight.unexpectedBracket.foreground': '#57606a',
		'editorBracketMatch.background': '#4ac26b40',
		'editorBracketMatch.border': '#4ac26b99',
		'editorCursor.foreground': '#0969da',
		'editorGroup.border': '#d0d7de',
		'editorGroupHeader.tabsBackground': '#f6f8fa',
		'editorGroupHeader.tabsBorder': '#d0d7de',
		'editorGutter.addedBackground': '#4ac26b66',
		'editorGutter.deletedBackground': '#ff818266',
		'editorGutter.modifiedBackground': '#d4a72c66',
		'editorIndentGuide.activeBackground': '#24292f3d',
		'editorIndentGuide.background': '#24292f1f',
		'editorInlayHint.background': '#afb8c133',
		'editorInlayHint.foreground': '#57606a',
		'editorInlayHint.typeBackground': '#afb8c133',
		'editorInlayHint.typeForeground': '#57606a',
		'editorLineNumber.activeForeground': '#24292f',
		'editorLineNumber.foreground': '#8c959f',
		'editorOverviewRuler.border': '#ffffff',
		'editorWhitespace.foreground': '#afb8c1',
		'editorWidget.background': '#ffffff',
		errorForeground: '#cf222e',
		focusBorder: '#0969da',
		foreground: '#24292f',
		'gitDecoration.addedResourceForeground': '#1a7f37',
		'gitDecoration.conflictingResourceForeground': '#bc4c00',
		'gitDecoration.deletedResourceForeground': '#cf222e',
		'gitDecoration.ignoredResourceForeground': '#6e7781',
		'gitDecoration.modifiedResourceForeground': '#9a6700',
		'gitDecoration.submoduleResourceForeground': '#57606a',
		'gitDecoration.untrackedResourceForeground': '#1a7f37',
		'icon.foreground': '#57606a',
		'input.background': '#ffffff',
		'input.border': '#d0d7de',
		'input.foreground': '#24292f',
		'input.placeholderForeground': '#6e7781',
		'keybindingLabel.foreground': '#24292f',
		'list.activeSelectionBackground': '#afb8c133',
		'list.activeSelectionForeground': '#24292f',
		'list.focusBackground': '#ddf4ff',
		'list.focusForeground': '#24292f',
		'list.highlightForeground': '#0969da',
		'list.hoverBackground': '#eaeef280',
		'list.hoverForeground': '#24292f',
		'list.inactiveFocusBackground': '#ddf4ff',
		'list.inactiveSelectionBackground': '#afb8c133',
		'list.inactiveSelectionForeground': '#24292f',
		'minimapSlider.activeBackground': '#8c959f47',
		'minimapSlider.background': '#8c959f33',
		'minimapSlider.hoverBackground': '#8c959f3d',
		'notificationCenterHeader.background': '#f6f8fa',
		'notificationCenterHeader.foreground': '#57606a',
		'notifications.background': '#ffffff',
		'notifications.border': '#d0d7de',
		'notifications.foreground': '#24292f',
		'notificationsErrorIcon.foreground': '#cf222e',
		'notificationsInfoIcon.foreground': '#0969da',
		'notificationsWarningIcon.foreground': '#9a6700',
		'panel.background': '#f6f8fa',
		'panel.border': '#d0d7de',
		'panelInput.border': '#d0d7de',
		'panelTitle.activeBorder': '#fd8c73',
		'panelTitle.activeForeground': '#24292f',
		'panelTitle.inactiveForeground': '#57606a',
		'pickerGroup.border': '#d0d7de',
		'pickerGroup.foreground': '#57606a',
		'progressBar.background': '#0969da',
		'quickInput.background': '#ffffff',
		'quickInput.foreground': '#24292f',
		'scrollbar.shadow': '#6e778133',
		'scrollbarSlider.activeBackground': '#8c959f47',
		'scrollbarSlider.background': '#8c959f33',
		'scrollbarSlider.hoverBackground': '#8c959f3d',
		'settings.headerForeground': '#24292f',
		'settings.modifiedItemIndicator': '#d4a72c66',
		'sideBar.background': '#f6f8fa',
		'sideBar.border': '#d0d7de',
		'sideBar.foreground': '#24292f',
		'sideBarSectionHeader.background': '#f6f8fa',
		'sideBarSectionHeader.border': '#d0d7de',
		'sideBarSectionHeader.foreground': '#24292f',
		'sideBarTitle.foreground': '#24292f',
		'statusBar.background': '#ffffff',
		'statusBar.border': '#d0d7de',
		'statusBar.debuggingBackground': '#cf222e',
		'statusBar.debuggingForeground': '#ffffff',
		'statusBar.focusBorder': '#0969da80',
		'statusBar.foreground': '#57606a',
		'statusBar.noFolderBackground': '#ffffff',
		'statusBarItem.activeBackground': '#24292f1f',
		'statusBarItem.focusBorder': '#0969da',
		'statusBarItem.hoverBackground': '#24292f14',
		'statusBarItem.prominentBackground': '#afb8c133',
		'statusBarItem.remoteBackground': '#0969da',
		'statusBarItem.remoteForeground': '#ffffff',
		'symbolIcon.arrayForeground': '#953800',
		'symbolIcon.booleanForeground': '#0550ae',
		'symbolIcon.classForeground': '#953800',
		'symbolIcon.colorForeground': '#0a3069',
		'symbolIcon.constantForeground': '#116329',
		'symbolIcon.constructorForeground': '#3e1f79',
		'symbolIcon.enumeratorForeground': '#953800',
		'symbolIcon.enumeratorMemberForeground': '#0550ae',
		'symbolIcon.eventForeground': '#57606a',
		'symbolIcon.fieldForeground': '#953800',
		'symbolIcon.fileForeground': '#7d4e00',
		'symbolIcon.folderForeground': '#7d4e00',
		'symbolIcon.functionForeground': '#6639ba',
		'symbolIcon.interfaceForeground': '#953800',
		'symbolIcon.keyForeground': '#0550ae',
		'symbolIcon.keywordForeground': '#a40e26',
		'symbolIcon.methodForeground': '#6639ba',
		'symbolIcon.moduleForeground': '#a40e26',
		'symbolIcon.namespaceForeground': '#a40e26',
		'symbolIcon.nullForeground': '#0550ae',
		'symbolIcon.numberForeground': '#116329',
		'symbolIcon.objectForeground': '#953800',
		'symbolIcon.operatorForeground': '#0a3069',
		'symbolIcon.packageForeground': '#953800',
		'symbolIcon.propertyForeground': '#953800',
		'symbolIcon.referenceForeground': '#0550ae',
		'symbolIcon.snippetForeground': '#0550ae',
		'symbolIcon.stringForeground': '#0a3069',
		'symbolIcon.structForeground': '#953800',
		'symbolIcon.textForeground': '#0a3069',
		'symbolIcon.typeParameterForeground': '#0a3069',
		'symbolIcon.unitForeground': '#0550ae',
		'symbolIcon.variableForeground': '#953800',
		'tab.activeBackground': '#ffffff',
		'tab.activeBorder': '#ffffff',
		'tab.activeBorderTop': '#fd8c73',
		'tab.activeForeground': '#24292f',
		'tab.border': '#d0d7de',
		'tab.hoverBackground': '#ffffff',
		'tab.inactiveBackground': '#f6f8fa',
		'tab.inactiveForeground': '#57606a',
		'tab.unfocusedActiveBorder': '#ffffff',
		'tab.unfocusedActiveBorderTop': '#d0d7de',
		'tab.unfocusedHoverBackground': '#eaeef280',
		'terminal.ansiBlack': '#24292f',
		'terminal.ansiBlue': '#0969da',
		'terminal.ansiBrightBlack': '#57606a',
		'terminal.ansiBrightBlue': '#218bff',
		'terminal.ansiBrightCyan': '#3192aa',
		'terminal.ansiBrightGreen': '#1a7f37',
		'terminal.ansiBrightMagenta': '#a475f9',
		'terminal.ansiBrightRed': '#a40e26',
		'terminal.ansiBrightWhite': '#8c959f',
		'terminal.ansiBrightYellow': '#633c01',
		'terminal.ansiCyan': '#1b7c83',
		'terminal.ansiGreen': '#116329',
		'terminal.ansiMagenta': '#8250df',
		'terminal.ansiRed': '#cf222e',
		'terminal.ansiWhite': '#6e7781',
		'terminal.ansiYellow': '#4d2d00',
		'terminal.foreground': '#24292f',
		'textBlockQuote.background': '#f6f8fa',
		'textBlockQuote.border': '#d0d7de',
		'textCodeBlock.background': '#afb8c133',
		'textLink.activeForeground': '#0969da',
		'textLink.foreground': '#0969da',
		'textPreformat.foreground': '#57606a',
		'textSeparator.foreground': '#d8dee4',
		'titleBar.activeBackground': '#ffffff',
		'titleBar.activeForeground': '#57606a',
		'titleBar.border': '#d0d7de',
		'titleBar.inactiveBackground': '#f6f8fa',
		'titleBar.inactiveForeground': '#57606a',
		'tree.indentGuidesStroke': '#d8dee4',
		'activityBar.dropBorder': '#24292f',
		'banner.background': '#71819133',
		'banner.foreground': '#24292f',
		'banner.iconForeground': '#1a85ff',
		'breadcrumb.background': '#ffffff',
		'button.separator': '#ffffff66',
		'charts.blue': '#1a85ff',
		'charts.foreground': '#24292f',
		'charts.green': '#388a34',
		'charts.lines': '#24292f80',
		'charts.orange': '#d18616',
		'charts.purple': '#652d90',
		'charts.red': '#e51400',
		'charts.yellow': '#bf8803',
		'checkbox.foreground': '#24292f',
		'checkbox.selectBackground': '#ffffff',
		'checkbox.selectBorder': '#ffffff',
		'commandCenter.activeBackground': '#00000014',
		'commandCenter.activeBorder': '#57606a4d',
		'commandCenter.activeForeground': '#57606a',
		'commandCenter.background': '#0000000d',
		'commandCenter.border': '#57606a33',
		'commandCenter.foreground': '#57606a',
		'commandCenter.inactiveBorder': '#57606a40',
		'commandCenter.inactiveForeground': '#57606a',
		'debugExceptionWidget.background': '#f1dfde',
		'debugExceptionWidget.border': '#a31515',
		'debugIcon.breakpointCurrentStackframeForeground': '#be8700',
		'debugIcon.breakpointDisabledForeground': '#848484',
		'debugIcon.breakpointStackframeForeground': '#89d185',
		'debugIcon.breakpointUnverifiedForeground': '#848484',
		'debugIcon.continueForeground': '#007acc',
		'debugIcon.disconnectForeground': '#a1260d',
		'debugIcon.pauseForeground': '#007acc',
		'debugIcon.restartForeground': '#388a34',
		'debugIcon.startForeground': '#388a34',
		'debugIcon.stepBackForeground': '#007acc',
		'debugIcon.stepIntoForeground': '#007acc',
		'debugIcon.stepOutForeground': '#007acc',
		'debugIcon.stepOverForeground': '#007acc',
		'debugIcon.stopForeground': '#a1260d',
		'debugView.exceptionLabelBackground': '#a31515',
		'debugView.exceptionLabelForeground': '#ffffff',
		'debugView.stateLabelBackground': '#88888844',
		'debugView.stateLabelForeground': '#24292f',
		'debugView.valueChangedHighlight': '#569cd6',
		'diffEditor.diagonalFill': '#22222233',
		disabledForeground: '#61616180',
		'editor.findRangeHighlightBackground': '#b4b4b44d',
		'editor.hoverHighlightBackground': '#add6ff26',
		'editor.inactiveSelectionBackground': '#add6ff80',
		'editor.inlineValuesBackground': '#ffc80033',
		'editor.inlineValuesForeground': '#00000080',
		'editor.lineHighlightBorder': '#eeeeee',
		'editor.rangeHighlightBackground': '#fdff0033',
		'editor.selectionBackground': '#add6ff',
		'editor.snippetFinalTabstopHighlightBorder': '#0a326480',
		'editor.snippetTabstopHighlightBackground': '#0a326433',
		'editor.symbolHighlightBackground': '#fae17d80',
		'editor.wordHighlightTextBackground': '#eaeef280',
		'editor.wordHighlightTextBorder': '#afb8c199',
		'editorActiveLineNumber.foreground': '#0b216f',
		'editorBracketPairGuide.activeBackground1': '#00000000',
		'editorBracketPairGuide.activeBackground2': '#00000000',
		'editorBracketPairGuide.activeBackground3': '#00000000',
		'editorBracketPairGuide.activeBackground4': '#00000000',
		'editorBracketPairGuide.activeBackground5': '#00000000',
		'editorBracketPairGuide.activeBackground6': '#00000000',
		'editorBracketPairGuide.background1': '#00000000',
		'editorBracketPairGuide.background2': '#00000000',
		'editorBracketPairGuide.background3': '#00000000',
		'editorBracketPairGuide.background4': '#00000000',
		'editorBracketPairGuide.background5': '#00000000',
		'editorBracketPairGuide.background6': '#00000000',
		'editorCodeLens.foreground': '#919191',
		'editorCommentsWidget.rangeActiveBackground': '#1a85ff1a',
		'editorCommentsWidget.rangeActiveBorder': '#1a85ff66',
		'editorCommentsWidget.rangeBackground': '#1a85ff1a',
		'editorCommentsWidget.rangeBorder': '#1a85ff66',
		'editorCommentsWidget.resolvedBorder': '#61616180',
		'editorCommentsWidget.unresolvedBorder': '#1a85ff',
		'editorError.foreground': '#e51400',
		'editorGhostText.foreground': '#00000077',
		'editorGroup.dropBackground': '#2677cb2e',
		'editorGroup.dropIntoPromptBackground': '#ffffff',
		'editorGroup.dropIntoPromptForeground': '#24292f',
		'editorGroupHeader.noTabsBackground': '#ffffff',
		'editorGutter.background': '#ffffff',
		'editorGutter.commentGlyphForground': '#24292f',
		'editorGutter.commentRangeForeground': '#a5afb933',
		'editorGutter.foldingControlForeground': '#57606a',
		'editorHint.foreground': '#6c6c6c',
		'editorHoverWidget.background': '#ffffff',
		'editorHoverWidget.border': '#c8c8c8',
		'editorHoverWidget.foreground': '#24292f',
		'editorHoverWidget.highlightForeground': '#0969da',
		'editorHoverWidget.statusBarBackground': '#f2f2f2',
		'editorInfo.foreground': '#1a85ff',
		'editorInlayHint.parameterBackground': '#afb8c133',
		'editorInlayHint.parameterForeground': '#57606a',
		'editorLightBulb.foreground': '#ddb100',
		'editorLightBulbAutoFix.foreground': '#007acc',
		'editorLink.activeForeground': '#0000ff',
		'editorMarkerNavigation.background': '#ffffff',
		'editorMarkerNavigationError.background': '#e51400',
		'editorMarkerNavigationError.headerBackground': '#e514001a',
		'editorMarkerNavigationInfo.background': '#1a85ff',
		'editorMarkerNavigationInfo.headerBackground': '#1a85ff1a',
		'editorMarkerNavigationWarning.background': '#bf8803',
		'editorMarkerNavigationWarning.headerBackground': '#bf88031a',
		'editorOverviewRuler.addedForeground': '#4ac26b3d',
		'editorOverviewRuler.bracketMatchForeground': '#a0a0a0',
		'editorOverviewRuler.commonContentForeground': '#60606066',
		'editorOverviewRuler.currentContentForeground': '#40c8ae80',
		'editorOverviewRuler.deletedForeground': '#ff81823d',
		'editorOverviewRuler.errorForeground': '#ff1212b3',
		'editorOverviewRuler.findMatchForeground': '#d186167e',
		'editorOverviewRuler.incomingContentForeground': '#40a6ff80',
		'editorOverviewRuler.infoForeground': '#1a85ff',
		'editorOverviewRuler.modifiedForeground': '#d4a72c3d',
		'editorOverviewRuler.rangeHighlightForeground': '#007acc99',
		'editorOverviewRuler.selectionHighlightForeground': '#a0a0a0cc',
		'editorOverviewRuler.warningForeground': '#bf8803',
		'editorOverviewRuler.wordHighlightForeground': '#a0a0a0cc',
		'editorOverviewRuler.wordHighlightStrongForeground': '#c0a0c0cc',
		'editorOverviewRuler.wordHighlightTextForeground': '#a0a0a0cc',
		'editorPane.background': '#ffffff',
		'editorRuler.foreground': '#d3d3d3',
		'editorStickyScroll.background': '#ffffff',
		'editorStickyScrollHover.background': '#f0f0f0',
		'editorSuggestWidget.background': '#ffffff',
		'editorSuggestWidget.border': '#c8c8c8',
		'editorSuggestWidget.focusHighlightForeground': '#0969da',
		'editorSuggestWidget.foreground': '#24292f',
		'editorSuggestWidget.highlightForeground': '#0969da',
		'editorSuggestWidget.selectedBackground': '#afb8c133',
		'editorSuggestWidget.selectedForeground': '#24292f',
		'editorSuggestWidgetStatus.foreground': '#24292f80',
		'editorUnicodeHighlight.background': '#cea33d14',
		'editorUnicodeHighlight.border': '#cea33d',
		'editorUnnecessaryCode.opacity': '#00000077',
		'editorWarning.foreground': '#bf8803',
		'editorWidget.border': '#c8c8c8',
		'editorWidget.foreground': '#24292f',
		'inputOption.activeBackground': '#0969da33',
		'inputOption.activeBorder': '#007acc',
		'inputOption.activeForeground': '#000000',
		'inputOption.hoverBackground': '#b8b8b850',
		'inputValidation.errorBackground': '#f2dede',
		'inputValidation.errorBorder': '#be1100',
		'inputValidation.infoBackground': '#d6ecf2',
		'inputValidation.infoBorder': '#007acc',
		'inputValidation.warningBackground': '#f6f5d2',
		'inputValidation.warningBorder': '#b89500',
		'interactive.activeCodeBorder': '#1a85ff',
		'interactive.inactiveCodeBorder': '#afb8c133',
		'keybindingLabel.background': '#dddddd66',
		'keybindingLabel.border': '#cccccc66',
		'keybindingLabel.bottomBorder': '#bbbbbb66',
		'keybindingTable.headerBackground': '#24292f0a',
		'keybindingTable.rowsBackground': '#24292f0a',
		'list.deemphasizedForeground': '#8e8e90',
		'list.dropBackground': '#d6ebff',
		'list.errorForeground': '#b01011',
		'list.filterMatchBackground': '#fae17d80',
		'list.focusHighlightForeground': '#0969da',
		'list.focusOutline': '#0969da',
		'list.invalidItemForeground': '#b89500',
		'list.warningForeground': '#855f00',
		'listFilterWidget.background': '#ffffff',
		'listFilterWidget.noMatchesOutline': '#be1100',
		'listFilterWidget.outline': '#00000000',
		'listFilterWidget.shadow': '#00000029',
		'markdown.extension.editor.codeSpan.background': '#00000000',
		'markdown.extension.editor.codeSpan.border': '#add6ff',
		'markdown.extension.editor.formattingMark.foreground': '#afb8c1',
		'markdown.extension.editor.trailingSpace.background': '#22222233',
		'menu.background': '#ffffff',
		'menu.foreground': '#24292f',
		'menu.selectionBackground': '#afb8c133',
		'menu.selectionForeground': '#24292f',
		'menu.separatorBackground': '#d4d4d4',
		'menubar.selectionBackground': '#b8b8b850',
		'menubar.selectionForeground': '#57606a',
		'merge.commonContentBackground': '#60606029',
		'merge.commonHeaderBackground': '#60606066',
		'merge.currentContentBackground': '#40c8ae33',
		'merge.currentHeaderBackground': '#40c8ae80',
		'merge.incomingContentBackground': '#40a6ff33',
		'merge.incomingHeaderBackground': '#40a6ff80',
		'mergeEditor.change.background': '#9bb95533',
		'mergeEditor.change.word.background': '#9ccc2c66',
		'mergeEditor.changeBase.background': '#ffcccc',
		'mergeEditor.changeBase.word.background': '#ffa3a3',
		'mergeEditor.conflict.handled.minimapOverViewRuler': '#adaca8ee',
		'mergeEditor.conflict.handledFocused.border': '#c1c1c1cc',
		'mergeEditor.conflict.handledUnfocused.border': '#86868649',
		'mergeEditor.conflict.input1.background': '#40c8ae33',
		'mergeEditor.conflict.input2.background': '#40a6ff33',
		'mergeEditor.conflict.unhandled.minimapOverViewRuler': '#fcba03',
		'mergeEditor.conflict.unhandledFocused.border': '#ffa600',
		'mergeEditor.conflict.unhandledUnfocused.border': '#ffa600',
		'mergeEditor.conflictingLines.background': '#ffea0047',
		'minimap.errorHighlight': '#ff1212b3',
		'minimap.findMatchHighlight': '#d18616',
		'minimap.foregroundOpacity': '#000000',
		'minimap.selectionHighlight': '#add6ff',
		'minimap.selectionOccurrenceHighlight': '#c9c9c9',
		'minimap.warningHighlight': '#bf8803',
		'minimapGutter.addedBackground': '#4ac26b66',
		'minimapGutter.deletedBackground': '#ff818266',
		'minimapGutter.modifiedBackground': '#d4a72c66',
		'notificationLink.foreground': '#0969da',
		'panel.dropBorder': '#24292f',
		'panelSection.border': '#d0d7de',
		'panelSection.dropBackground': '#2677cb2e',
		'panelSectionHeader.background': '#80808033',
		'peekView.border': '#1a85ff',
		'peekViewEditor.background': '#f2f8fc',
		'peekViewEditor.matchHighlightBackground': '#f5d802de',
		'peekViewEditorGutter.background': '#f2f8fc',
		'peekViewEditorStickScroll.background': '#f2f8fc',
		'peekViewResult.background': '#f3f3f3',
		'peekViewResult.fileForeground': '#1e1e1e',
		'peekViewResult.lineForeground': '#646465',
		'peekViewResult.matchHighlightBackground': '#ea5c004d',
		'peekViewResult.selectionBackground': '#3399ff33',
		'peekViewResult.selectionForeground': '#6c6c6c',
		'peekViewTitle.background': '#1a85ff1a',
		'peekViewTitleDescription.foreground': '#616161',
		'peekViewTitleLabel.foreground': '#000000',
		'ports.iconRunningProcessForeground': '#0969da',
		'problemsErrorIcon.foreground': '#e51400',
		'problemsInfoIcon.foreground': '#1a85ff',
		'problemsWarningIcon.foreground': '#bf8803',
		'pullRequests.closed': '#cb2431',
		'pullRequests.draft': '#6e7681',
		'pullRequests.merged': '#8957e5',
		'pullRequests.notification': '#0969da',
		'pullRequests.open': '#3fb950',
		'quickInputList.focusBackground': '#afb8c133',
		'quickInputList.focusForeground': '#24292f',
		'quickInputTitle.background': '#0000000f',
		'rust_analyzer.syntaxTreeBorder': '#b700ff',
		'sash.hoverBorder': '#0969da',
		'scm.providerBorder': '#c8c8c8',
		'searchEditor.findMatchBackground': '#fae17d54',
		'searchEditor.textInputBorder': '#d0d7de',
		'settings.checkboxBackground': '#f6f8fa',
		'settings.checkboxBorder': '#d0d7de',
		'settings.checkboxForeground': '#24292f',
		'settings.dropdownBackground': '#ffffff',
		'settings.dropdownBorder': '#d0d7de',
		'settings.dropdownForeground': '#24292f',
		'settings.dropdownListBorder': '#c8c8c8',
		'settings.focusedRowBackground': '#eaeef24d',
		'settings.focusedRowBorder': '#0969da',
		'settings.headerBorder': '#d0d7de',
		'settings.numberInputBackground': '#ffffff',
		'settings.numberInputBorder': '#d0d7de',
		'settings.numberInputForeground': '#24292f',
		'settings.rowHoverBackground': '#eaeef227',
		'settings.sashBorder': '#d0d7de',
		'settings.settingsHeaderHoverForeground': '#24292fb3',
		'settings.textInputBackground': '#ffffff',
		'settings.textInputBorder': '#d0d7de',
		'settings.textInputForeground': '#24292f',
		'sideBar.dropBackground': '#2677cb2e',
		'sideBySideEditor.horizontalBorder': '#d0d7de',
		'sideBySideEditor.verticalBorder': '#d0d7de',
		'statusBar.debuggingBorder': '#d0d7de',
		'statusBar.noFolderBorder': '#d0d7de',
		'statusBar.noFolderForeground': '#57606a',
		'statusBarItem.compactHoverBackground': '#ffffff33',
		'statusBarItem.errorBackground': '#7c141b',
		'statusBarItem.errorForeground': '#ffffff',
		'statusBarItem.prominentForeground': '#57606a',
		'statusBarItem.prominentHoverBackground': '#0000004d',
		'statusBarItem.warningBackground': '#725102',
		'statusBarItem.warningForeground': '#ffffff',
		'tab.activeModifiedBorder': '#33aaee',
		'tab.inactiveModifiedBorder': '#33aaee80',
		'tab.lastPinnedBorder': '#d8dee4',
		'tab.unfocusedActiveBackground': '#ffffff',
		'tab.unfocusedActiveForeground': '#24292fb3',
		'tab.unfocusedActiveModifiedBorder': '#33aaeeb3',
		'tab.unfocusedInactiveBackground': '#f6f8fa',
		'tab.unfocusedInactiveForeground': '#57606a80',
		'tab.unfocusedInactiveModifiedBorder': '#33aaee40',
		'terminal.border': '#d0d7de',
		'terminal.dropBackground': '#2677cb2e',
		'terminal.findMatchBackground': '#bf8700',
		'terminal.findMatchHighlightBackground': '#fae17d80',
		'terminal.inactiveSelectionBackground': '#add6ff80',
		'terminal.selectionBackground': '#add6ff',
		'terminal.tab.activeBorder': '#ffffff',
		'terminalCommandDecoration.defaultBackground': '#00000040',
		'terminalCommandDecoration.errorBackground': '#e51400',
		'terminalCommandDecoration.successBackground': '#2090d3',
		'terminalOverviewRuler.cursorForeground': '#a0a0a0cc',
		'terminalOverviewRuler.findMatchForeground': '#d186167e',
		'testing.iconErrored': '#f14c4c',
		'testing.iconFailed': '#f14c4c',
		'testing.iconPassed': '#73c991',
		'testing.iconQueued': '#cca700',
		'testing.iconSkipped': '#848484',
		'testing.iconUnset': '#848484',
		'testing.message.error.decorationForeground': '#e51400',
		'testing.message.error.lineBackground': '#ff000033',
		'testing.message.info.decorationForeground': '#24292f80',
		'testing.peekBorder': '#e51400',
		'testing.peekHeaderBackground': '#e514001a',
		'testing.runAction': '#73c991',
		'toolbar.activeBackground': '#a6a6a650',
		'toolbar.hoverBackground': '#b8b8b850',
		'tree.inactiveIndentGuidesStroke': '#d8dee466',
		'tree.tableColumnsBorder': '#61616120',
		'tree.tableOddRowsBackground': '#24292f0a',
		'walkthrough.stepTitle.foreground': '#000000',
		'welcomeOverlay.background': '#ffffff85',
		'welcomePage.progress.background': '#ffffff',
		'welcomePage.progress.foreground': '#0969da',
		'welcomePage.tileBackground': '#ffffff',
		'welcomePage.tileBorder': '#0000001a',
		'welcomePage.tileHoverBackground': '#e6e6e6',
		'widget.shadow': '#00000029',
	},
});
monaco.editor.defineTheme('github-dark', {
	base: 'vs-dark',
	inherit: false,
	rules: [
		{
			foreground: '8B949E',
			token: 'comment',
		},
		{
			foreground: '8B949E',
			token: 'punctuation.definition.comment',
		},
		{
			foreground: '8B949E',
			token: 'string.comment',
		},
		{
			foreground: 'FF7B72',
			token: 'constant.other.placeholder',
		},
		{
			foreground: 'FF7B72',
			token: 'constant.character',
		},
		{
			foreground: '79C0FF',
			token: 'constant',
		},
		{
			foreground: '79C0FF',
			token: 'entity.name.constant',
		},
		{
			foreground: '79C0FF',
			token: 'variable.other.constant',
		},
		{
			foreground: '79C0FF',
			token: 'variable.other.enummember',
		},
		{
			foreground: '79C0FF',
			token: 'variable.language',
		},
		{
			foreground: '79C0FF',
			token: 'entity',
		},
		{
			foreground: 'FFA657',
			token: 'entity.name',
		},
		{
			foreground: 'FFA657',
			token: 'meta.export.default',
		},
		{
			foreground: 'FFA657',
			token: 'meta.definition.variable',
		},
		{
			foreground: 'C9D1D9',
			token: 'variable.parameter.function',
		},
		{
			foreground: 'C9D1D9',
			token: 'meta.jsx.children',
		},
		{
			foreground: 'C9D1D9',
			token: 'meta.block',
		},
		{
			foreground: 'C9D1D9',
			token: 'meta.tag.attributes',
		},
		{
			foreground: 'C9D1D9',
			token: 'entity.name.constant',
		},
		{
			foreground: 'C9D1D9',
			token: 'meta.object.member',
		},
		{
			foreground: 'C9D1D9',
			token: 'meta.embedded.expression',
		},
		{
			foreground: 'D2A8FF',
			token: 'entity.name.function',
		},
		{
			foreground: '7EE787',
			token: 'entity.name.tag',
		},
		{
			foreground: '7EE787',
			token: 'support.class.component',
		},
		{
			foreground: 'FF7B72',
			token: 'keyword',
		},
		{
			foreground: 'FF7B72',
			token: 'storage',
		},
		{
			foreground: 'FF7B72',
			token: 'storage.type',
		},
		{
			foreground: 'C9D1D9',
			token: 'storage.modifier.package',
		},
		{
			foreground: 'C9D1D9',
			token: 'storage.modifier.import',
		},
		{
			foreground: 'C9D1D9',
			token: 'storage.type.java',
		},
		{
			foreground: 'A5D6FF',
			token: 'string',
		},
		{
			foreground: 'A5D6FF',
			token: 'string punctuation.section.embedded source',
		},
		{
			foreground: '79C0FF',
			token: 'support',
		},
		{
			foreground: '79C0FF',
			token: 'meta.property-name',
		},
		{
			foreground: 'FFA657',
			token: 'variable',
		},
		{
			foreground: 'C9D1D9',
			token: 'variable.other',
		},
		{
			foreground: 'FFA198',
			fontStyle: 'italic',
			token: 'invalid.broken',
		},
		{
			foreground: 'FFA198',
			fontStyle: 'italic',
			token: 'invalid.deprecated',
		},
		{
			foreground: 'FFA198',
			fontStyle: 'italic',
			token: 'invalid.illegal',
		},
		{
			foreground: 'FFA198',
			fontStyle: 'italic',
			token: 'invalid.unimplemented',
		},
		{
			foreground: 'F0F6FC',
			background: 'FF7B72',
			fontStyle: 'italic underline',
			token: 'carriage-return',
		},
		{
			foreground: 'FFA198',
			token: 'message.error',
		},
		{
			foreground: '79C0FF',
			token: 'string variable',
		},
		{
			foreground: 'A5D6FF',
			token: 'source.regexp',
		},
		{
			foreground: 'A5D6FF',
			token: 'string.regexp',
		},
		{
			foreground: 'A5D6FF',
			token: 'string.regexp.character-class',
		},
		{
			foreground: 'A5D6FF',
			token: 'string.regexp constant.character.escape',
		},
		{
			foreground: 'A5D6FF',
			token: 'string.regexp source.ruby.embedded',
		},
		{
			foreground: 'A5D6FF',
			token: 'string.regexp string.regexp.arbitrary-repitition',
		},
		{
			foreground: '7EE787',
			fontStyle: 'bold',
			token: 'string.regexp constant.character.escape',
		},
		{
			foreground: '79C0FF',
			token: 'support.constant',
		},
		{
			foreground: '79C0FF',
			token: 'support.variable',
		},
		{
			foreground: '7EE787',
			token: 'support.type.property-name.json',
		},
		{
			foreground: '79C0FF',
			token: 'meta.module-reference',
		},
		{
			foreground: 'FFA657',
			token: 'punctuation.definition.list.begin.markdown',
		},
		{
			foreground: '79C0FF',
			fontStyle: 'bold',
			token: 'markup.heading',
		},
		{
			foreground: '79C0FF',
			fontStyle: 'bold',
			token: 'markup.heading entity.name',
		},
		{
			foreground: '7EE787',
			token: 'markup.quote',
		},
		{
			foreground: 'C9D1D9',
			fontStyle: 'italic',
			token: 'markup.italic',
		},
		{
			foreground: 'C9D1D9',
			fontStyle: 'bold',
			token: 'markup.bold',
		},
		{
			fontStyle: 'underline',
			token: 'markup.underline',
		},
		{
			fontStyle: 'strikethrough',
			token: 'markup.strikethrough',
		},
		{
			foreground: '79C0FF',
			token: 'markup.inline.raw',
		},
		{
			foreground: 'FFA198',
			background: '490202',
			token: 'markup.deleted',
		},
		{
			foreground: 'FFA198',
			background: '490202',
			token: 'meta.diff.header.from-file',
		},
		{
			foreground: 'FFA198',
			background: '490202',
			token: 'punctuation.definition.deleted',
		},
		{
			foreground: 'FF7B72',
			token: 'punctuation.section.embedded',
		},
		{
			foreground: '7EE787',
			background: '04260F',
			token: 'markup.inserted',
		},
		{
			foreground: '7EE787',
			background: '04260F',
			token: 'meta.diff.header.to-file',
		},
		{
			foreground: '7EE787',
			background: '04260F',
			token: 'punctuation.definition.inserted',
		},
		{
			foreground: 'FFA657',
			background: '5A1E02',
			token: 'markup.changed',
		},
		{
			foreground: 'FFA657',
			background: '5A1E02',
			token: 'punctuation.definition.changed',
		},
		{
			foreground: '161B22',
			background: '79C0FF',
			token: 'markup.ignored',
		},
		{
			foreground: '161B22',
			background: '79C0FF',
			token: 'markup.untracked',
		},
		{
			foreground: 'D2A8FF',
			fontStyle: 'bold',
			token: 'meta.diff.range',
		},
		{
			foreground: '79C0FF',
			token: 'meta.diff.header',
		},
		{
			foreground: '79C0FF',
			fontStyle: 'bold',
			token: 'meta.separator',
		},
		{
			foreground: '79C0FF',
			token: 'meta.output',
		},
		{
			foreground: '8B949E',
			token: 'brackethighlighter.tag',
		},
		{
			foreground: '8B949E',
			token: 'brackethighlighter.curly',
		},
		{
			foreground: '8B949E',
			token: 'brackethighlighter.round',
		},
		{
			foreground: '8B949E',
			token: 'brackethighlighter.square',
		},
		{
			foreground: '8B949E',
			token: 'brackethighlighter.angle',
		},
		{
			foreground: '8B949E',
			token: 'brackethighlighter.quote',
		},
		{
			foreground: 'FFA198',
			token: 'brackethighlighter.unmatched',
		},
		{
			foreground: 'A5D6FF',
			token: 'constant.other.reference.link',
		},
		{
			foreground: 'A5D6FF',
			token: 'string.other.link',
		},
		{
			foreground: '6796E6',
			token: 'token.info-token',
		},
		{
			foreground: 'CD9731',
			token: 'token.warn-token',
		},
		{
			foreground: 'F44747',
			token: 'token.error-token',
		},
		{
			foreground: 'B267E6',
			token: 'token.debug-token',
		},
	],
	colors: {
		'activityBar.activeBorder': '#f78166',
		'activityBar.background': '#0d1117',
		'activityBar.border': '#30363d',
		'activityBar.foreground': '#c9d1d9',
		'activityBar.inactiveForeground': '#8b949e',
		'activityBarBadge.background': '#1f6feb',
		'activityBarBadge.foreground': '#ffffff',
		'badge.background': '#1f6feb',
		'badge.foreground': '#ffffff',
		'breadcrumb.activeSelectionForeground': '#8b949e',
		'breadcrumb.focusForeground': '#c9d1d9',
		'breadcrumb.foreground': '#8b949e',
		'breadcrumbPicker.background': '#161b22',
		'button.background': '#238636',
		'button.foreground': '#ffffff',
		'button.hoverBackground': '#2ea043',
		'button.secondaryBackground': '#282e33',
		'button.secondaryForeground': '#c9d1d9',
		'button.secondaryHoverBackground': '#30363d',
		'checkbox.background': '#161b22',
		'checkbox.border': '#30363d',
		'debugConsole.errorForeground': '#ffa198',
		'debugConsole.infoForeground': '#8b949e',
		'debugConsole.sourceForeground': '#e3b341',
		'debugConsole.warningForeground': '#d29922',
		'debugConsoleInputIcon.foreground': '#bc8cff',
		'debugIcon.breakpointForeground': '#f85149',
		'debugTokenExpression.boolean': '#56d364',
		'debugTokenExpression.error': '#ffa198',
		'debugTokenExpression.name': '#79c0ff',
		'debugTokenExpression.number': '#56d364',
		'debugTokenExpression.string': '#a5d6ff',
		'debugTokenExpression.value': '#a5d6ff',
		'debugToolBar.background': '#161b22',
		descriptionForeground: '#8b949e',
		'diffEditor.insertedLineBackground': '#23863626',
		'diffEditor.insertedTextBackground': '#3fb9504d',
		'diffEditor.removedLineBackground': '#da363326',
		'diffEditor.removedTextBackground': '#ff7b724d',
		'dropdown.background': '#161b22',
		'dropdown.border': '#30363d',
		'dropdown.foreground': '#c9d1d9',
		'dropdown.listBackground': '#161b22',
		'editor.background': '#0d1117',
		'editor.findMatchBackground': '#9e6a03',
		'editor.findMatchHighlightBackground': '#f2cc6080',
		'editor.focusedStackFrameHighlightBackground': '#2ea04366',
		'editor.foldBackground': '#6e76811a',
		'editor.foreground': '#c9d1d9',
		'editor.lineHighlightBackground': '#6e76811a',
		'editor.linkedEditingBackground': '#58a6ff12',
		'editor.selectionHighlightBackground': '#3fb95040',
		'editor.stackFrameHighlightBackground': '#bb800966',
		'editor.wordHighlightBackground': '#6e768180',
		'editor.wordHighlightBorder': '#6e768199',
		'editor.wordHighlightStrongBackground': '#6e76814d',
		'editor.wordHighlightStrongBorder': '#6e768199',
		'editorBracketHighlight.foreground1': '#79c0ff',
		'editorBracketHighlight.foreground2': '#56d364',
		'editorBracketHighlight.foreground3': '#e3b341',
		'editorBracketHighlight.foreground4': '#ffa198',
		'editorBracketHighlight.foreground5': '#ff9bce',
		'editorBracketHighlight.foreground6': '#d2a8ff',
		'editorBracketHighlight.unexpectedBracket.foreground': '#8b949e',
		'editorBracketMatch.background': '#3fb95040',
		'editorBracketMatch.border': '#3fb95099',
		'editorCursor.foreground': '#58a6ff',
		'editorGroup.border': '#30363d',
		'editorGroupHeader.tabsBackground': '#010409',
		'editorGroupHeader.tabsBorder': '#30363d',
		'editorGutter.addedBackground': '#2ea04366',
		'editorGutter.deletedBackground': '#f8514966',
		'editorGutter.modifiedBackground': '#bb800966',
		'editorIndentGuide.activeBackground': '#c9d1d93d',
		'editorIndentGuide.background': '#c9d1d91f',
		'editorInlayHint.background': '#8b949e33',
		'editorInlayHint.foreground': '#8b949e',
		'editorInlayHint.typeBackground': '#8b949e33',
		'editorInlayHint.typeForeground': '#8b949e',
		'editorLineNumber.activeForeground': '#c9d1d9',
		'editorLineNumber.foreground': '#6e7681',
		'editorOverviewRuler.border': '#010409',
		'editorWhitespace.foreground': '#484f58',
		'editorWidget.background': '#161b22',
		errorForeground: '#f85149',
		focusBorder: '#1f6feb',
		foreground: '#c9d1d9',
		'gitDecoration.addedResourceForeground': '#3fb950',
		'gitDecoration.conflictingResourceForeground': '#db6d28',
		'gitDecoration.deletedResourceForeground': '#f85149',
		'gitDecoration.ignoredResourceForeground': '#6e7681',
		'gitDecoration.modifiedResourceForeground': '#d29922',
		'gitDecoration.submoduleResourceForeground': '#8b949e',
		'gitDecoration.untrackedResourceForeground': '#3fb950',
		'icon.foreground': '#8b949e',
		'input.background': '#0d1117',
		'input.border': '#30363d',
		'input.foreground': '#c9d1d9',
		'input.placeholderForeground': '#6e7681',
		'keybindingLabel.foreground': '#c9d1d9',
		'list.activeSelectionBackground': '#6e768166',
		'list.activeSelectionForeground': '#c9d1d9',
		'list.focusBackground': '#388bfd26',
		'list.focusForeground': '#c9d1d9',
		'list.highlightForeground': '#58a6ff',
		'list.hoverBackground': '#6e76811a',
		'list.hoverForeground': '#c9d1d9',
		'list.inactiveFocusBackground': '#388bfd26',
		'list.inactiveSelectionBackground': '#6e768166',
		'list.inactiveSelectionForeground': '#c9d1d9',
		'minimapSlider.activeBackground': '#8b949e47',
		'minimapSlider.background': '#8b949e33',
		'minimapSlider.hoverBackground': '#8b949e3d',
		'notificationCenterHeader.background': '#161b22',
		'notificationCenterHeader.foreground': '#8b949e',
		'notifications.background': '#161b22',
		'notifications.border': '#30363d',
		'notifications.foreground': '#c9d1d9',
		'notificationsErrorIcon.foreground': '#f85149',
		'notificationsInfoIcon.foreground': '#58a6ff',
		'notificationsWarningIcon.foreground': '#d29922',
		'panel.background': '#010409',
		'panel.border': '#30363d',
		'panelInput.border': '#30363d',
		'panelTitle.activeBorder': '#f78166',
		'panelTitle.activeForeground': '#c9d1d9',
		'panelTitle.inactiveForeground': '#8b949e',
		'peekViewEditor.background': '#6e76811a',
		'peekViewEditor.matchHighlightBackground': '#bb800966',
		'peekViewResult.background': '#0d1117',
		'peekViewResult.matchHighlightBackground': '#bb800966',
		'pickerGroup.border': '#30363d',
		'pickerGroup.foreground': '#8b949e',
		'progressBar.background': '#1f6feb',
		'quickInput.background': '#161b22',
		'quickInput.foreground': '#c9d1d9',
		'scrollbar.shadow': '#484f5833',
		'scrollbarSlider.activeBackground': '#8b949e47',
		'scrollbarSlider.background': '#8b949e33',
		'scrollbarSlider.hoverBackground': '#8b949e3d',
		'settings.headerForeground': '#c9d1d9',
		'settings.modifiedItemIndicator': '#bb800966',
		'sideBar.background': '#010409',
		'sideBar.border': '#30363d',
		'sideBar.foreground': '#c9d1d9',
		'sideBarSectionHeader.background': '#010409',
		'sideBarSectionHeader.border': '#30363d',
		'sideBarSectionHeader.foreground': '#c9d1d9',
		'sideBarTitle.foreground': '#c9d1d9',
		'statusBar.background': '#0d1117',
		'statusBar.border': '#30363d',
		'statusBar.debuggingBackground': '#da3633',
		'statusBar.debuggingForeground': '#ffffff',
		'statusBar.focusBorder': '#1f6feb80',
		'statusBar.foreground': '#8b949e',
		'statusBar.noFolderBackground': '#0d1117',
		'statusBarItem.activeBackground': '#c9d1d91f',
		'statusBarItem.focusBorder': '#1f6feb',
		'statusBarItem.hoverBackground': '#c9d1d914',
		'statusBarItem.prominentBackground': '#6e768166',
		'statusBarItem.remoteBackground': '#0969da',
		'statusBarItem.remoteForeground': '#ffffff',
		'symbolIcon.arrayForeground': '#f0883e',
		'symbolIcon.booleanForeground': '#58a6ff',
		'symbolIcon.classForeground': '#f0883e',
		'symbolIcon.colorForeground': '#79c0ff',
		'symbolIcon.constructorForeground': '#d2a8ff',
		'symbolIcon.enumeratorForeground': '#f0883e',
		'symbolIcon.enumeratorMemberForeground': '#58a6ff',
		'symbolIcon.eventForeground': '#6e7681',
		'symbolIcon.fieldForeground': '#f0883e',
		'symbolIcon.fileForeground': '#d29922',
		'symbolIcon.folderForeground': '#d29922',
		'symbolIcon.functionForeground': '#bc8cff',
		'symbolIcon.interfaceForeground': '#f0883e',
		'symbolIcon.keyForeground': '#58a6ff',
		'symbolIcon.keywordForeground': '#ff7b72',
		'symbolIcon.methodForeground': '#bc8cff',
		'symbolIcon.moduleForeground': '#ff7b72',
		'symbolIcon.namespaceForeground': '#ff7b72',
		'symbolIcon.nullForeground': '#58a6ff',
		'symbolIcon.numberForeground': '#3fb950',
		'symbolIcon.objectForeground': '#f0883e',
		'symbolIcon.operatorForeground': '#79c0ff',
		'symbolIcon.packageForeground': '#f0883e',
		'symbolIcon.propertyForeground': '#f0883e',
		'symbolIcon.referenceForeground': '#58a6ff',
		'symbolIcon.snippetForeground': '#58a6ff',
		'symbolIcon.stringForeground': '#79c0ff',
		'symbolIcon.structForeground': '#f0883e',
		'symbolIcon.textForeground': '#79c0ff',
		'symbolIcon.typeParameterForeground': '#79c0ff',
		'symbolIcon.unitForeground': '#58a6ff',
		'symbolIcon.variableForeground': '#f0883e',
		'tab.activeBackground': '#0d1117',
		'tab.activeBorder': '#0d1117',
		'tab.activeBorderTop': '#f78166',
		'tab.activeForeground': '#c9d1d9',
		'tab.border': '#30363d',
		'tab.hoverBackground': '#0d1117',
		'tab.inactiveBackground': '#010409',
		'tab.inactiveForeground': '#8b949e',
		'tab.unfocusedActiveBorder': '#0d1117',
		'tab.unfocusedActiveBorderTop': '#30363d',
		'tab.unfocusedHoverBackground': '#6e76811a',
		'terminal.ansiBlack': '#484f58',
		'terminal.ansiBlue': '#58a6ff',
		'terminal.ansiBrightBlack': '#6e7681',
		'terminal.ansiBrightBlue': '#79c0ff',
		'terminal.ansiBrightCyan': '#56d4dd',
		'terminal.ansiBrightGreen': '#56d364',
		'terminal.ansiBrightMagenta': '#d2a8ff',
		'terminal.ansiBrightRed': '#ffa198',
		'terminal.ansiBrightWhite': '#ffffff',
		'terminal.ansiBrightYellow': '#e3b341',
		'terminal.ansiCyan': '#39c5cf',
		'terminal.ansiGreen': '#3fb950',
		'terminal.ansiMagenta': '#bc8cff',
		'terminal.ansiRed': '#ff7b72',
		'terminal.ansiWhite': '#b1bac4',
		'terminal.ansiYellow': '#d29922',
		'terminal.foreground': '#c9d1d9',
		'textBlockQuote.background': '#010409',
		'textBlockQuote.border': '#30363d',
		'textCodeBlock.background': '#6e768166',
		'textLink.activeForeground': '#58a6ff',
		'textLink.foreground': '#58a6ff',
		'textPreformat.foreground': '#8b949e',
		'textSeparator.foreground': '#21262d',
		'titleBar.activeBackground': '#0d1117',
		'titleBar.activeForeground': '#8b949e',
		'titleBar.border': '#30363d',
		'titleBar.inactiveBackground': '#010409',
		'titleBar.inactiveForeground': '#8b949e',
		'tree.indentGuidesStroke': '#21262d',
		'activityBar.dropBorder': '#c9d1d9',
		'banner.background': '#6e768166',
		'banner.foreground': '#c9d1d9',
		'banner.iconForeground': '#3794ff',
		'breadcrumb.background': '#0d1117',
		'button.separator': '#ffffff66',
		'charts.blue': '#3794ff',
		'charts.foreground': '#c9d1d9',
		'charts.green': '#89d185',
		'charts.lines': '#c9d1d980',
		'charts.orange': '#d18616',
		'charts.purple': '#b180d7',
		'charts.red': '#f14c4c',
		'charts.yellow': '#cca700',
		'checkbox.foreground': '#c9d1d9',
		'checkbox.selectBackground': '#161b22',
		'checkbox.selectBorder': '#161b22',
		'commandCenter.activeBackground': '#ffffff14',
		'commandCenter.activeBorder': '#8b949e4d',
		'commandCenter.activeForeground': '#8b949e',
		'commandCenter.background': '#ffffff0d',
		'commandCenter.border': '#8b949e33',
		'commandCenter.foreground': '#8b949e',
		'commandCenter.inactiveBorder': '#8b949e40',
		'commandCenter.inactiveForeground': '#8b949e',
		'debugExceptionWidget.background': '#420b0d',
		'debugExceptionWidget.border': '#a31515',
		'debugIcon.breakpointCurrentStackframeForeground': '#ffcc00',
		'debugIcon.breakpointDisabledForeground': '#848484',
		'debugIcon.breakpointStackframeForeground': '#89d185',
		'debugIcon.breakpointUnverifiedForeground': '#848484',
		'debugIcon.continueForeground': '#75beff',
		'debugIcon.disconnectForeground': '#f48771',
		'debugIcon.pauseForeground': '#75beff',
		'debugIcon.restartForeground': '#89d185',
		'debugIcon.startForeground': '#89d185',
		'debugIcon.stepBackForeground': '#75beff',
		'debugIcon.stepIntoForeground': '#75beff',
		'debugIcon.stepOutForeground': '#75beff',
		'debugIcon.stepOverForeground': '#75beff',
		'debugIcon.stopForeground': '#f48771',
		'debugView.exceptionLabelBackground': '#6c2022',
		'debugView.exceptionLabelForeground': '#c9d1d9',
		'debugView.stateLabelBackground': '#88888844',
		'debugView.stateLabelForeground': '#c9d1d9',
		'debugView.valueChangedHighlight': '#569cd6',
		'diffEditor.diagonalFill': '#cccccc33',
		disabledForeground: '#cccccc80',
		'editor.findRangeHighlightBackground': '#3a3d4166',
		'editor.hoverHighlightBackground': '#264f7840',
		'editor.inactiveSelectionBackground': '#264f7880',
		'editor.inlineValuesBackground': '#ffc80033',
		'editor.inlineValuesForeground': '#ffffff80',
		'editor.lineHighlightBorder': '#282828',
		'editor.rangeHighlightBackground': '#ffffff0b',
		'editor.selectionBackground': '#264f78',
		'editor.snippetFinalTabstopHighlightBorder': '#525252',
		'editor.snippetTabstopHighlightBackground': '#7c7c7c4d',
		'editor.symbolHighlightBackground': '#f2cc6080',
		'editor.wordHighlightTextBackground': '#6e768180',
		'editor.wordHighlightTextBorder': '#6e768199',
		'editorActiveLineNumber.foreground': '#c6c6c6',
		'editorBracketPairGuide.activeBackground1': '#00000000',
		'editorBracketPairGuide.activeBackground2': '#00000000',
		'editorBracketPairGuide.activeBackground3': '#00000000',
		'editorBracketPairGuide.activeBackground4': '#00000000',
		'editorBracketPairGuide.activeBackground5': '#00000000',
		'editorBracketPairGuide.activeBackground6': '#00000000',
		'editorBracketPairGuide.background1': '#00000000',
		'editorBracketPairGuide.background2': '#00000000',
		'editorBracketPairGuide.background3': '#00000000',
		'editorBracketPairGuide.background4': '#00000000',
		'editorBracketPairGuide.background5': '#00000000',
		'editorBracketPairGuide.background6': '#00000000',
		'editorCodeLens.foreground': '#999999',
		'editorCommentsWidget.rangeActiveBackground': '#3794ff1a',
		'editorCommentsWidget.rangeActiveBorder': '#3794ff66',
		'editorCommentsWidget.rangeBackground': '#3794ff1a',
		'editorCommentsWidget.rangeBorder': '#3794ff66',
		'editorCommentsWidget.resolvedBorder': '#cccccc80',
		'editorCommentsWidget.unresolvedBorder': '#3794ff',
		'editorError.foreground': '#f14c4c',
		'editorGhostText.foreground': '#ffffff56',
		'editorGroup.dropBackground': '#53595d80',
		'editorGroup.dropIntoPromptBackground': '#161b22',
		'editorGroup.dropIntoPromptForeground': '#c9d1d9',
		'editorGroupHeader.noTabsBackground': '#0d1117',
		'editorGutter.background': '#0d1117',
		'editorGutter.commentGlyphForground': '#c9d1d9',
		'editorGutter.commentRangeForeground': '#6e768166',
		'editorGutter.foldingControlForeground': '#8b949e',
		'editorHint.foreground': '#eeeeeeb3',
		'editorHoverWidget.background': '#161b22',
		'editorHoverWidget.border': '#454545',
		'editorHoverWidget.foreground': '#c9d1d9',
		'editorHoverWidget.highlightForeground': '#58a6ff',
		'editorHoverWidget.statusBarBackground': '#1a2029',
		'editorInfo.foreground': '#3794ff',
		'editorInlayHint.parameterBackground': '#8b949e33',
		'editorInlayHint.parameterForeground': '#8b949e',
		'editorLightBulb.foreground': '#ffcc00',
		'editorLightBulbAutoFix.foreground': '#75beff',
		'editorLink.activeForeground': '#4e94ce',
		'editorMarkerNavigation.background': '#0d1117',
		'editorMarkerNavigationError.background': '#f14c4c',
		'editorMarkerNavigationError.headerBackground': '#f14c4c1a',
		'editorMarkerNavigationInfo.background': '#3794ff',
		'editorMarkerNavigationInfo.headerBackground': '#3794ff1a',
		'editorMarkerNavigationWarning.background': '#cca700',
		'editorMarkerNavigationWarning.headerBackground': '#cca7001a',
		'editorOverviewRuler.addedForeground': '#2ea0433d',
		'editorOverviewRuler.bracketMatchForeground': '#a0a0a0',
		'editorOverviewRuler.commonContentForeground': '#60606066',
		'editorOverviewRuler.currentContentForeground': '#40c8ae80',
		'editorOverviewRuler.deletedForeground': '#f851493d',
		'editorOverviewRuler.errorForeground': '#ff1212b3',
		'editorOverviewRuler.findMatchForeground': '#d186167e',
		'editorOverviewRuler.incomingContentForeground': '#40a6ff80',
		'editorOverviewRuler.infoForeground': '#3794ff',
		'editorOverviewRuler.modifiedForeground': '#bb80093d',
		'editorOverviewRuler.rangeHighlightForeground': '#007acc99',
		'editorOverviewRuler.selectionHighlightForeground': '#a0a0a0cc',
		'editorOverviewRuler.warningForeground': '#cca700',
		'editorOverviewRuler.wordHighlightForeground': '#a0a0a0cc',
		'editorOverviewRuler.wordHighlightStrongForeground': '#c0a0c0cc',
		'editorOverviewRuler.wordHighlightTextForeground': '#a0a0a0cc',
		'editorPane.background': '#0d1117',
		'editorRuler.foreground': '#5a5a5a',
		'editorStickyScroll.background': '#0d1117',
		'editorStickyScrollHover.background': '#2a2d2e',
		'editorSuggestWidget.background': '#161b22',
		'editorSuggestWidget.border': '#454545',
		'editorSuggestWidget.focusHighlightForeground': '#58a6ff',
		'editorSuggestWidget.foreground': '#c9d1d9',
		'editorSuggestWidget.highlightForeground': '#58a6ff',
		'editorSuggestWidget.selectedBackground': '#6e768166',
		'editorSuggestWidget.selectedForeground': '#c9d1d9',
		'editorSuggestWidgetStatus.foreground': '#c9d1d980',
		'editorUnicodeHighlight.background': '#bd9b0326',
		'editorUnicodeHighlight.border': '#bd9b03',
		'editorUnnecessaryCode.opacity': '#000000aa',
		'editorWarning.foreground': '#cca700',
		'editorWidget.border': '#454545',
		'editorWidget.foreground': '#c9d1d9',
		'extensionBadge.remoteBackground': '#1f6feb',
		'extensionBadge.remoteForeground': '#ffffff',
		'extensionButton.background': '#238636',
		'extensionButton.foreground': '#ffffff',
		'extensionButton.hoverBackground': '#2ea043',
		'extensionButton.prominentBackground': '#238636',
		'extensionButton.prominentForeground': '#ffffff',
		'extensionButton.prominentHoverBackground': '#2ea043',
		'extensionButton.separator': '#ffffff66',
		'extensionIcon.preReleaseForeground': '#1d9271',
		'extensionIcon.sponsorForeground': '#d758b3',
		'extensionIcon.starForeground': '#ff8e00',
		'extensionIcon.verifiedForeground': '#58a6ff',
		'gitDecoration.renamedResourceForeground': '#73c991',
		'gitDecoration.stageDeletedResourceForeground': '#c74e39',
		'gitDecoration.stageModifiedResourceForeground': '#e2c08d',
		'gitlens.closedAutolinkedIssueIconColor': '#a371f7',
		'gitlens.closedPullRequestIconColor': '#f85149',
		'gitlens.decorations.addedForegroundColor': '#3fb950',
		'gitlens.decorations.branchAheadForegroundColor': '#35b15e',
		'gitlens.decorations.branchBehindForegroundColor': '#b15e35',
		'gitlens.decorations.branchDivergedForegroundColor': '#d8af1b',
		'gitlens.decorations.branchMissingUpstreamForegroundColor': '#c74e39',
		'gitlens.decorations.branchUnpublishedForegroundColor': '#35b15e',
		'gitlens.decorations.branchUpToDateForegroundColor': '#c9d1d9',
		'gitlens.decorations.copiedForegroundColor': '#73c991',
		'gitlens.decorations.deletedForegroundColor': '#f85149',
		'gitlens.decorations.ignoredForegroundColor': '#6e7681',
		'gitlens.decorations.modifiedForegroundColor': '#d29922',
		'gitlens.decorations.renamedForegroundColor': '#73c991',
		'gitlens.decorations.untrackedForegroundColor': '#3fb950',
		'gitlens.decorations.worktreeView.hasUncommittedChangesForegroundColor':
			'#e2c08d',
		'gitlens.graphLane10Color': '#2ece9d',
		'gitlens.graphLane1Color': '#15a0bf',
		'gitlens.graphLane2Color': '#0669f7',
		'gitlens.graphLane3Color': '#8e00c2',
		'gitlens.graphLane4Color': '#c517b6',
		'gitlens.graphLane5Color': '#d90171',
		'gitlens.graphLane6Color': '#cd0101',
		'gitlens.graphLane7Color': '#f25d2e',
		'gitlens.graphLane8Color': '#f2ca33',
		'gitlens.graphLane9Color': '#7bd938',
		'gitlens.gutterBackgroundColor': '#ffffff13',
		'gitlens.gutterForegroundColor': '#bebebe',
		'gitlens.gutterUncommittedForegroundColor': '#00bcf299',
		'gitlens.lineHighlightBackgroundColor': '#00bcf233',
		'gitlens.lineHighlightOverviewRulerColor': '#00bcf299',
		'gitlens.mergedPullRequestIconColor': '#a371f7',
		'gitlens.openAutolinkedIssueIconColor': '#3fb950',
		'gitlens.openPullRequestIconColor': '#3fb950',
		'gitlens.trailingLineBackgroundColor': '#00000000',
		'gitlens.trailingLineForegroundColor': '#99999959',
		'gitlens.unpublishedChangesIconColor': '#35b15e',
		'gitlens.unpublishedCommitIconColor': '#35b15e',
		'gitlens.unpulledChangesIconColor': '#b15e35',
		'inputOption.activeBackground': '#1f6feb66',
		'inputOption.activeBorder': '#007acc',
		'inputOption.activeForeground': '#ffffff',
		'inputOption.hoverBackground': '#5a5d5e80',
		'inputValidation.errorBackground': '#5a1d1d',
		'inputValidation.errorBorder': '#be1100',
		'inputValidation.infoBackground': '#063b49',
		'inputValidation.infoBorder': '#007acc',
		'inputValidation.warningBackground': '#352a05',
		'inputValidation.warningBorder': '#b89500',
		'interactive.activeCodeBorder': '#3794ff',
		'interactive.inactiveCodeBorder': '#6e768166',
		'issues.closed': '#cb2431',
		'issues.newIssueDecoration': '#ffffff48',
		'issues.open': '#3fb950',
		'keybindingLabel.background': '#8080802b',
		'keybindingLabel.border': '#33333399',
		'keybindingLabel.bottomBorder': '#44444499',
		'keybindingTable.headerBackground': '#c9d1d90a',
		'keybindingTable.rowsBackground': '#c9d1d90a',
		'list.deemphasizedForeground': '#8c8c8c',
		'list.dropBackground': '#062f4a',
		'list.errorForeground': '#f88070',
		'list.filterMatchBackground': '#f2cc6080',
		'list.focusHighlightForeground': '#58a6ff',
		'list.focusOutline': '#1f6feb',
		'list.invalidItemForeground': '#b89500',
		'list.warningForeground': '#cca700',
		'listFilterWidget.background': '#161b22',
		'listFilterWidget.noMatchesOutline': '#be1100',
		'listFilterWidget.outline': '#00000000',
		'listFilterWidget.shadow': '#0000005c',
		'markdown.extension.editor.codeSpan.background': '#00000000',
		'markdown.extension.editor.codeSpan.border': '#264f78',
		'markdown.extension.editor.formattingMark.foreground': '#484f58',
		'markdown.extension.editor.trailingSpace.background': '#cccccc33',
		'menu.background': '#161b22',
		'menu.foreground': '#c9d1d9',
		'menu.selectionBackground': '#6e768166',
		'menu.selectionForeground': '#c9d1d9',
		'menu.separatorBackground': '#606060',
		'menubar.selectionBackground': '#5a5d5e50',
		'menubar.selectionForeground': '#8b949e',
		'merge.commonContentBackground': '#60606029',
		'merge.commonHeaderBackground': '#60606066',
		'merge.currentContentBackground': '#40c8ae33',
		'merge.currentHeaderBackground': '#40c8ae80',
		'merge.incomingContentBackground': '#40a6ff33',
		'merge.incomingHeaderBackground': '#40a6ff80',
		'mergeEditor.change.background': '#9bb95533',
		'mergeEditor.change.word.background': '#9ccc2c33',
		'mergeEditor.changeBase.background': '#4b1818',
		'mergeEditor.changeBase.word.background': '#6f1313',
		'mergeEditor.conflict.handled.minimapOverViewRuler': '#adaca8ee',
		'mergeEditor.conflict.handledFocused.border': '#c1c1c1cc',
		'mergeEditor.conflict.handledUnfocused.border': '#86868649',
		'mergeEditor.conflict.input1.background': '#40c8ae33',
		'mergeEditor.conflict.input2.background': '#40a6ff33',
		'mergeEditor.conflict.unhandled.minimapOverViewRuler': '#fcba03',
		'mergeEditor.conflict.unhandledFocused.border': '#ffa600',
		'mergeEditor.conflict.unhandledUnfocused.border': '#ffa6007a',
		'mergeEditor.conflictingLines.background': '#ffea0047',
		'minimap.errorHighlight': '#ff1212b3',
		'minimap.findMatchHighlight': '#d18616',
		'minimap.foregroundOpacity': '#000000',
		'minimap.selectionHighlight': '#264f78',
		'minimap.selectionOccurrenceHighlight': '#676767',
		'minimap.warningHighlight': '#cca700',
		'minimapGutter.addedBackground': '#2ea04366',
		'minimapGutter.deletedBackground': '#f8514966',
		'minimapGutter.modifiedBackground': '#bb800966',
		'notebook.cellBorderColor': '#6e768166',
		'notebook.cellEditorBackground': '#010409',
		'notebook.cellInsertionIndicator': '#1f6feb',
		'notebook.cellStatusBarItemHoverBackground': '#ffffff26',
		'notebook.cellToolbarSeparator': '#80808059',
		'notebook.editorBackground': '#0d1117',
		'notebook.focusedCellBorder': '#1f6feb',
		'notebook.focusedEditorBorder': '#1f6feb',
		'notebook.inactiveFocusedCellBorder': '#6e768166',
		'notebook.selectedCellBackground': '#6e768166',
		'notebook.selectedCellBorder': '#6e768166',
		'notebook.symbolHighlightBackground': '#ffffff0b',
		'notebookEditorOverviewRuler.runningCellForeground': '#89d185',
		'notebookScrollbarSlider.activeBackground': '#8b949e47',
		'notebookScrollbarSlider.background': '#8b949e33',
		'notebookScrollbarSlider.hoverBackground': '#8b949e3d',
		'notebookStatusErrorIcon.foreground': '#f85149',
		'notebookStatusRunningIcon.foreground': '#c9d1d9',
		'notebookStatusSuccessIcon.foreground': '#89d185',
		'notificationLink.foreground': '#58a6ff',
		'panel.dropBorder': '#c9d1d9',
		'panelSection.border': '#30363d',
		'panelSection.dropBackground': '#53595d80',
		'panelSectionHeader.background': '#80808033',
		'peekView.border': '#3794ff',
		'peekViewEditorGutter.background': '#6e76811a',
		'peekViewEditorStickScroll.background': '#6e76811a',
		'peekViewResult.fileForeground': '#ffffff',
		'peekViewResult.lineForeground': '#bbbbbb',
		'peekViewResult.selectionBackground': '#3399ff33',
		'peekViewResult.selectionForeground': '#ffffff',
		'peekViewTitle.background': '#3794ff1a',
		'peekViewTitleDescription.foreground': '#ccccccb3',
		'peekViewTitleLabel.foreground': '#ffffff',
		'ports.iconRunningProcessForeground': '#0969da',
		'problemsErrorIcon.foreground': '#f14c4c',
		'problemsInfoIcon.foreground': '#3794ff',
		'problemsWarningIcon.foreground': '#cca700',
		'pullRequests.closed': '#cb2431',
		'pullRequests.draft': '#6e7681',
		'pullRequests.merged': '#8957e5',
		'pullRequests.notification': '#58a6ff',
		'pullRequests.open': '#3fb950',
		'quickInputList.focusBackground': '#6e768166',
		'quickInputList.focusForeground': '#c9d1d9',
		'quickInputTitle.background': '#ffffff1b',
		'rust_analyzer.syntaxTreeBorder': '#ffffff',
		'sash.hoverBorder': '#1f6feb',
		'scm.providerBorder': '#454545',
		'searchEditor.findMatchBackground': '#f2cc6054',
		'searchEditor.textInputBorder': '#30363d',
		'settings.checkboxBackground': '#161b22',
		'settings.checkboxBorder': '#30363d',
		'settings.checkboxForeground': '#c9d1d9',
		'settings.dropdownBackground': '#161b22',
		'settings.dropdownBorder': '#30363d',
		'settings.dropdownForeground': '#c9d1d9',
		'settings.dropdownListBorder': '#454545',
		'settings.focusedRowBackground': '#6e768110',
		'settings.focusedRowBorder': '#1f6feb',
		'settings.headerBorder': '#30363d',
		'settings.numberInputBackground': '#0d1117',
		'settings.numberInputBorder': '#30363d',
		'settings.numberInputForeground': '#c9d1d9',
		'settings.rowHoverBackground': '#6e768108',
		'settings.sashBorder': '#30363d',
		'settings.settingsHeaderHoverForeground': '#c9d1d9b3',
		'settings.textInputBackground': '#0d1117',
		'settings.textInputBorder': '#30363d',
		'settings.textInputForeground': '#c9d1d9',
		'sideBar.dropBackground': '#53595d80',
		'sideBySideEditor.horizontalBorder': '#30363d',
		'sideBySideEditor.verticalBorder': '#30363d',
		'statusBar.debuggingBorder': '#30363d',
		'statusBar.noFolderBorder': '#30363d',
		'statusBar.noFolderForeground': '#8b949e',
		'statusBarItem.compactHoverBackground': '#ffffff33',
		'statusBarItem.errorBackground': '#b91007',
		'statusBarItem.errorForeground': '#ffffff',
		'statusBarItem.prominentForeground': '#8b949e',
		'statusBarItem.prominentHoverBackground': '#0000004d',
		'statusBarItem.warningBackground': '#7a6400',
		'statusBarItem.warningForeground': '#ffffff',
		'symbolIcon.constantForeground': '#c9d1d9',
		'tab.activeModifiedBorder': '#3399cc',
		'tab.inactiveModifiedBorder': '#3399cc80',
		'tab.lastPinnedBorder': '#21262d',
		'tab.unfocusedActiveBackground': '#0d1117',
		'tab.unfocusedActiveForeground': '#c9d1d980',
		'tab.unfocusedActiveModifiedBorder': '#3399cc80',
		'tab.unfocusedInactiveBackground': '#010409',
		'tab.unfocusedInactiveForeground': '#8b949e80',
		'tab.unfocusedInactiveModifiedBorder': '#3399cc40',
		'terminal.border': '#30363d',
		'terminal.dropBackground': '#53595d80',
		'terminal.findMatchBackground': '#9e6a03',
		'terminal.findMatchHighlightBackground': '#f2cc6080',
		'terminal.inactiveSelectionBackground': '#264f7880',
		'terminal.selectionBackground': '#264f78',
		'terminal.tab.activeBorder': '#0d1117',
		'terminalCommandDecoration.defaultBackground': '#ffffff40',
		'terminalCommandDecoration.errorBackground': '#f14c4c',
		'terminalCommandDecoration.successBackground': '#1b81a8',
		'terminalOverviewRuler.cursorForeground': '#a0a0a0cc',
		'terminalOverviewRuler.findMatchForeground': '#d186167e',
		'testing.iconErrored': '#f14c4c',
		'testing.iconFailed': '#f14c4c',
		'testing.iconPassed': '#73c991',
		'testing.iconQueued': '#cca700',
		'testing.iconSkipped': '#848484',
		'testing.iconUnset': '#848484',
		'testing.message.error.decorationForeground': '#f14c4c',
		'testing.message.error.lineBackground': '#ff000033',
		'testing.message.info.decorationForeground': '#c9d1d980',
		'testing.peekBorder': '#f14c4c',
		'testing.peekHeaderBackground': '#f14c4c1a',
		'testing.runAction': '#73c991',
		'toolbar.activeBackground': '#63666750',
		'toolbar.hoverBackground': '#5a5d5e50',
		'tree.inactiveIndentGuidesStroke': '#21262d66',
		'tree.tableColumnsBorder': '#cccccc20',
		'tree.tableOddRowsBackground': '#c9d1d90a',
		'walkthrough.stepTitle.foreground': '#ffffff',
		'welcomeOverlay.background': '#00000085',
		'welcomePage.progress.background': '#0d1117',
		'welcomePage.progress.foreground': '#58a6ff',
		'welcomePage.tileBackground': '#161b22',
		'welcomePage.tileBorder': '#ffffff1a',
		'welcomePage.tileHoverBackground': '#1a2029',
		'widget.shadow': '#0000005c',
	},
});
monaco.editor.setTheme('github');
